---
- name: "install EPEL GPG key - if specified"
  rpm_key:
    key: "{{ monitoring_host_epel_gpg_download_url }}"
    state: present
  when:
    - monitoring_host_epel_gpg_download_url is defined
    - monitoring_host_epel_gpg_download_url|trim != ''
    - monitoring_host_epel_disable_gpg_check|lower == 'no'

- name: "install epel-release"
  yum:
    name: "{{ monitoring_host_epel_download_url }}"
    state: present
    disable_gpg_check: "{{ monitoring_host_epel_disable_gpg_check | default('no') }}"

- name: Ensure epel-release is installed
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - epel-release

- name: Ensure pip is installed
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - python-pip

- name: Install required python libraries
  pip:
    name: "docker-py"
    state: present

- name: create editors group for prometheus
  group:
    name: monitoring-editors
    state: present

- name: create editor user
  user:
    name: monitoring-edit-user-1
    group: monitoring-editors

- name: generate ssh key
  command: ssh-keygen -f /tmp/monitoring-edit-user-1_key -P ""
  delegate_to: localhost
  become: no
  ignore_errors: true
  
- name: add the new key to editor users authorized keys
  authorized_key:
    key: "{{ lookup('file', '/tmp/monitoring-edit-user-1_key.pub') }}"
    user: monitoring-edit-user-1

- name: create targets directory
  file:
    path: "/var/prometheus_targets"
    state: directory
    mode: '0775'
    group: monitoring-editors
    seuser: system_u
    setype: container_file_t

- name: 'Open Firewall for scraping'
  firewalld:
    port: "{{ prometheus_port }}/tcp"
    permanent: yes
    state: enabled
    immediate: yes
